### ISSUE TITLE
Show camera grid

### ISSUE THREAD

**Issue by Raph33** [Horizontal-org/Tella-Android#10]
Show the grid in the camera to help users get better shots

**Comment by joc-a** [comment]
I would like to work on this issue.
Do you want the grid to always be there? Or you want a button to show/hide it or maybe a switch in the settings?

**Comment by Raph33** [comment]
Great @joc-a!
Let's add a button to show/hide the grid in the camera view, in the app bar next to the "switch camera" and "flash" buttons. We can use [this icon when the grid is on](https://material.io/resources/icons/?search=grid&icon=grid_on&style=baseline) and [this one when it's off](https://material.io/resources/icons/?search=grid&icon=grid_off&style=baseline)

**Comment by joc-a** [comment]
https://github.com/Horizontal-org/Tella-Android/pull/30

**Comment by tomislavr** [comment]
Closed with https://github.com/Horizontal-org/Tella-Android/pull/30.
