### ISSUE TITLE
Create new "list view" for Gallery

### ISSUE THREAD

**Issue by raphmim** [Horizontal-org/Tella-Android#13]
The list view will allow users to have access to more information about the files directly from the Gallery, such as file type, size, and creation date

**Comment by sophiastr** [comment]
i am working on the issue.

**Comment by sophiastr** [comment]
I am interested in contributing to the project you are developing.
Do you still need help?

**Comment by raphmim** [comment]
@sophiastr we have actually developed this internally, so I will close this issue.

But we will be releasing a new version of Tella just next week, with a number of new features and issues coming up!
