### ISSUE TITLE
Cannot share audio from Tella to Signal

### ISSUE THREAD

**Issue by mk-tbl** [Horizontal-org/Tella-Android#144]
## Expected behavior

Share audio recording to Signal.

## Actual behavior

After attempting to share to Signal, the 'send' button in Signal does nothing. Same happens when sharing to Line or WhatsApp. When attempting to save the file to local device, creates an empty file (size 0 bytes).

## Steps to reproduce the problem

1. Record audio file in Tella.
2. Press menu button next to audio file name and select 'share'.
3. Select Signal recipient.
4. Press 'send' button in Signal.

## Additional information

This worked perfectly in previous versions of Tella, but now does not work at all.

**Comment by raphmim** [comment]
hello @mk-tbl

We are aware of this issue and are actively working to fix it. In the meantime, could you try the following:
1. Go to Settings > Security > Lock timeout
2. Set the lock timeout to 5 minutes
3. Try to share again through Signal or other third party app

Does this work?

**Comment by ahlem-jarrar** [comment]
This problem is fixed within the release (V2.0.10 "125")
