### ISSUE TITLE
Transifex link doesn't work

### ISSUE THREAD

**Issue by elimisteve** [Horizontal-org/Tella-Android#181]
## Describe the change

In `README.md`, the link to https://www.transifex.com/otf/tella/dashboard/ takes us to a page saying that the project has been archived. Thus, we can't contribute to translations.

How about pointing to a working Transifex page or removing the link altogether?

## How will this impact users?

They'll no longer be directed to a not-exactly-useful page on transifex.com :slightly_smiling_face:  .

## To which release does this apply?

- [x] Current release
- [x] Future release

**Comment by carohadad** [comment]
Hi @elimisteve !! I'm sorry we didn't see this on time, and thank you so much for the feedback.

I have updated the Readme with the new translation page we are using: https://github.com/Horizontal-org/Tella-Android#translating

Also, we just launched a new documentation platform (that will be translated soon!) with more details about how to contribute to the translation of Tella :) https://docs.tella-app.org/translating-tella

Please email us if you have any questions or would like to chat about better language support in Tella :)
