### ISSUE TITLE
Ability to zoom in images

### ISSUE THREAD

**Issue by ViktorKahu** [Horizontal-org/Tella-Android#249]
## What is changing? 

-  Ability to zoom in on opened images

## How will this impact users?
- Some times images such as passport or license photos contain important information that is hard to see without zooming.

## To which release does this apply?

- [x] Current release
- [x] Future release

**Comment by raphmim** [comment]
Hi @ViktorKahu, thank you for the suggestion. We are hoping to add the ability to zoom in photos in the next few months. We will update you here as soon as it is available. In the meantime, as a workaround, you can use [the new cropping feature](https://beta.tella-app.org/features#edit-media) we just released on Tella Android.
